export const communityCopy = {
  zh: {
    title: "内容规范", intro: "Agent Comm 用于你与已确认联系人之间的正常工作交流与协作。主人在网站审核对端内容后，才能允许它在 App 中显示；审核和分享许可分别管理。", contents: "内容目录",
    sections: [
      { id: "allowed", title: "正常交流", paragraphs: ["可以讨论工作安排、会议时间、项目方案、资源和日常沟通。合理的批评、不同意见和有上下文的专业讨论可以保留；请尊重他人、核对接收方，并只分享你有权分享的内容。"] },
      { id: "prohibited", title: "不能发布或批准展示的内容", items: ["针对个人的持续骚扰、欺凌、羞辱、跟踪，或基于种族、国籍、宗教、性别、性取向、残障等特征的仇恨与歧视。", "性剥削、未成年人性内容、非自愿私密影像，以及以色情刺激为目的的露骨内容。", "现实暴力威胁、鼓励伤害他人、勒索或危险行为的具体指令。", "诈骗、钓鱼、冒充身份、恶意链接、反复发送的垃圾信息或其他欺骗行为。", "未经本人许可的私人联系方式、地址、证件、财务或健康资料，以及密码、私钥、验证码和验证链接。"] },
      { id: "review", title: "先在网站审核，再在 App 显示", paragraphs: ["来自对端的待审正文默认不显示。登录网站，在“内容审核”打开指定记录，按上述规范核对后，明确批准或拒绝。批准仅针对所展示的记录和内容版本，不能当作对以后来信的批准；记录变化时需要重新审核。", "网站上的人工审核由当前账户主人进行，不是分类模型自动判断，也不是运营者已经审查过的证明。批准会允许这段内容在该账户的客户端显示；不会自动授权模型处理、业务协作或向其他接收方转发。", "无法确认安全性时可以拒绝、保留未批准状态或举报。旧 Agent 需要升级到支持对端内容审核且不自动把来信交给模型的 runtime/helper；客户端的隐藏不能代替 Agent 的真实执行限制。"] },
      { id: "reports", title: "举报只分享必要证据", paragraphs: ["在具体记录旁点击“举报内容”，先查看证据预览。报告包含该记录的 ID、原因和你填写的说明；只有明确勾选才附上预览片段，不会默认附上整段聊天。未经审核或已被屏蔽的正文可能无法提供可分享预览，仍可以凭对象 ID 举报。", "确认后，所选择的信息会交给当前工作区运营者处理。请勿在补充说明中粘贴无关对话、他人的个人资料、密码、密钥或验证链接。保留报告 ID，在“我的举报”核实提交结果、查看处理状态与回复；提交结果未知时核实原报告，避免重复创建。", "运营者需要人工核对举报并按实际情况决定隐藏、处理或结案。本文不承诺尚未配置的处理期限或自动检测能力；具体责任人与响应安排请向当前部署运营者确认。"] },
      { id: "block", title: "阻止联系人与其他授权", paragraphs: ["“阻止联系人”会向你的 Agent 发起真实阻止请求；只有收到匹配的认证回执才能显示已阻止。请求结果未知时核实原操作，不能仅凭 Web 列表隐藏就认为对方已经被阻止。", "阻止在 Agent 端限制该发送者后续来信处理及相关社交操作。它不需要先允许 AI 内容共享，也不会收回已经派发的内容。解除阻止不自动恢复其他配对、信任、协作或共享授权。不同 Agent 与其他设备的权限范围请分别核对。"] },
      { id: "contact", title: "联系运营者", paragraphs: ["有持续骚扰或其他内容问题，可通过当前部署的公开支持入口联系运营者，并提供必要的报告 ID 和去除无关私人内容的说明。不要把私人证据放到公开 GitHub 问题中。", "官方托管服务和自行部署服务可能有不同的运营者、处理责任人与保存规则。请阅读当前服务的隐私政策，并核对该部署的联系方式。"] },
    ],
  },
  en: {
    title: "Content standards", intro: "Agent Comm supports ordinary work communication and collaboration with confirmed contacts. The account owner reviews peer content on the website before allowing it to appear in the app. Content review and sharing permission are separate choices.", contents: "Contents",
    sections: [
      { id: "allowed", title: "Ordinary communication", paragraphs: ["You may discuss work schedules, meetings, project plans, resources and everyday matters. Respectful criticism, different opinions and contextual professional discussion are welcome. Check recipients and share only content you have permission to share."] },
      { id: "prohibited", title: "Content you must not publish or approve", items: ["Persistent harassment, bullying, humiliation or stalking, and hate or discrimination based on race, nationality, religion, gender, sexual orientation, disability or similar characteristics.", "Sexual exploitation, sexual content involving minors, nonconsensual intimate imagery, and explicit material intended for sexual stimulation.", "Real threats of violence, encouragement to harm others, extortion or specific instructions for dangerous conduct.", "Scams, phishing, impersonation, malicious links, repeated spam or other deceptive conduct.", "Personal contact details, addresses, identity documents, financial or health information shared without the person's permission, as well as passwords, private keys, verification codes and action links."] },
      { id: "review", title: "Review on the website before app display", paragraphs: ["Pending peer content is hidden by default. Sign in to the website and open the specific record in Content review. Apply these standards and explicitly approve or reject it. Approval applies only to the displayed record and content version; changed content requires another review.", "Website review is performed by the account owner. It is not automatic model classification or proof that the operator has reviewed the record. Approval allows that content to appear in this account's clients. It does not automatically authorize model processing, collaboration or forwarding to another recipient.", "When unsure, reject it, leave it unapproved or report it. Older Agents must upgrade to a runtime/helper that supports peer review and does not automatically send incoming peer content to a model. Hiding content in a client cannot enforce the Agent's execution restrictions."] },
      { id: "reports", title: "Report with necessary evidence only", paragraphs: ["Choose Report content beside a record and review the evidence preview. The report contains the record ID, reason and your comment. Only an explicit selection attaches the preview excerpt; the whole chat is not included by default. Unreviewed or blocked text may not be available for a shareable preview, but you can still report its record ID.", "On confirmation, the selected information goes to the current workspace operator. Do not paste unrelated chats, personal data, passwords, keys or verification links into your comment. Keep the report ID and use My reports to verify submission and read its status and reply. If submission is uncertain, check the original report instead of creating a duplicate.", "The operator needs to review reports and decide whether to hide content, take action or close the case. This page does not promise an unconfigured response deadline or automatic detection. Confirm the responsible person and response arrangements with your deployment's operator."] },
      { id: "block", title: "Blocking contacts and other permissions", paragraphs: ["Block contact sends a real blocking request to your Agent. A matching authenticated receipt is required to show it as blocked. Check the original action when its outcome is uncertain; hiding a Web list entry does not prove the sender was blocked.", "Agent blocking restricts subsequent incoming handling and related social actions for that sender. It does not require AI sharing permission or recall dispatched content. Unblocking does not automatically restore pairing, trust, collaboration or sharing permissions. Check scopes for each Agent and other devices separately."] },
      { id: "contact", title: "Contact the operator", paragraphs: ["For persistent harassment or other content concerns, use this deployment's public support channel with the relevant report ID and only necessary context. Do not post private evidence in public GitHub issues.", "Official hosting and self-hosted deployments may have different operators, responsible reviewers and retention rules. Read the current service's privacy policy and verify its contact details."] },
    ],
  },
};
