const assert=require("node:assert/strict"),test=require("node:test"),fs=require("node:fs"),path=require("node:path"),Module=require("node:module"),ts=require("typescript");
function load(relative,deps={}){const filename=path.resolve(__dirname,relative),m=new Module(filename,module);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));m.require=name=>Object.hasOwn(deps,name)?deps[name]:Module.prototype.require.call(m,name);m._compile(ts.transpileModule(fs.readFileSync(filename,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,filename);return m.exports;}
function hooks(){const slots=[],pending=[],cleanups=[];let index=0;return{React:{useState(initial){const key=index++;if(!(key in slots))slots[key]=initial;return[slots[key],value=>slots[key]=typeof value==="function"?value(slots[key]):value]},useRef(initial){const key=index++;if(!(key in slots))slots[key]={current:initial};return slots[key]},useEffect(fn,deps){const key=index++;if(!slots[key]||deps.some((value,i)=>!Object.is(value,slots[key][i]))){slots[key]=deps;pending.push(fn)}}},render(fn){index=0;return fn()},flush(){for(const fn of pending.splice(0)){const cleanup=fn();if(cleanup)cleanups.push(cleanup)}},close(){for(const cleanup of cleanups)cleanup()}};}
function text(node){if(node==null)return"";if(Array.isArray(node))return node.map(text).join("");if(typeof node!=="object")return String(node);return text(node.props?.children);}
function find(node,predicate){if(!node||typeof node!=="object")return null;if(Array.isArray(node)){for(const item of node){const match=find(item,predicate);if(match)return match}return null}return predicate(node)?node:find(node.props?.children,predicate);}
const button=(tree,label)=>find(tree,node=>node.type==="button"&&text(node)===label);
async function settle(){for(let index=0;index<8;index++)await new Promise(done=>setImmediate(done));}
function fixture(){const runtime=hooks(),events=new Map(),previous={fetch:global.fetch,window:global.window};let user={id:"owner",sessionVersion:1,loginSessionId:"login"},item={id:"828d8507-cdf1-4578-b472-6d410ecec293",agentId:"agent",target:{kind:"inbox",id:"message"},digest:"a".repeat(64),status:"pending"};global.window={addEventListener:(name,fn)=>events.set(name,fn),removeEventListener:name=>events.delete(name)};const jsx=(type,props,key)=>({type,props,key}),component=load("../../src/components/content-review-page.tsx",{react:runtime.React,"react/jsx-runtime":{jsx,jsxs:jsx,Fragment:"fragment"},"next/navigation":{useSearchParams:()=>new URLSearchParams("agentId=agent")},"next/link":{default:"link"},"next-auth/react":{getSession:async()=>user?{user}:null},"@/components/ui/button":{Button:"button"},"@/lib/control/workbench-client":load("../../src/lib/control/workbench-client.ts")});return{events,get item(){return item},setStatus(status){item={...item,status}},setUser(value){user=value},read(url){return Response.json(url.includes("/workspace")?{snapshots:{capabilities:{data:{methods:[]}}}}:{items:[item]})},render(){const tree=runtime.render(()=>component.ContentReviewPage());runtime.flush();return tree},close(){runtime.close();Object.assign(global,previous)}};}
test("the actual content-review page never reveals a preview that completed after blur",async()=>{const f=fixture();let resolve;const pending=new Promise(done=>resolve=done);global.fetch=async(url,init)=>{if(init?.method==="POST"){await pending;return Response.json({item:f.item,body:{text:"private delayed peer evidence"},previewToken:"token"})}return f.read(url)};try{f.render();await settle();button(f.render(),"我理解风险，查看这份内容").props.onClick();await settle();f.events.get("blur")();resolve();await settle();assert.doesNotMatch(text(f.render()),/private delayed peer evidence/)}finally{f.close()}});
test("the actual content-review page clears old evidence and refuses a decision after a session switch",async()=>{const f=fixture();let decisions=0;global.fetch=async(url,init)=>{if(init?.method==="POST"){const body=JSON.parse(init.body);if(body.action==="decide")decisions++;return Response.json({item:f.item,body:{text:"private previous-session evidence"},previewToken:"token"})}return f.read(url)};try{f.render();await settle();button(f.render(),"我理解风险，查看这份内容").props.onClick();await settle();let tree=f.render();assert.match(text(tree),/private previous-session evidence/);find(tree,node=>node.type==="input").props.onChange({target:{checked:true}});tree=f.render();f.setUser({id:"other",sessionVersion:1,loginSessionId:"other-login"});button(tree,"内容合适，允许 App 展示").props.onClick();await settle();assert.equal(decisions,0);assert.doesNotMatch(text(f.render()),/private previous-session evidence/)}finally{f.close()}});
test("a lost website approval is reconciled by queue reads without a second POST, including after focus hides its preview",async()=>{const f=fixture();let decisions=0;global.fetch=async(url,init)=>{if(init?.method==="POST"){const body=JSON.parse(init.body);if(body.action==="preview")return Response.json({item:f.item,body:{text:"private evidence"},previewToken:"token"});decisions++;f.setStatus("approved");throw Error("lost after commit")}return f.read(url)};try{f.render();await settle();button(f.render(),"我理解风险，查看这份内容").props.onClick();await settle();let tree=f.render();find(tree,node=>node.type==="input").props.onChange({target:{checked:true}});button(f.render(),"内容合适，允许 App 展示").props.onClick();await settle();assert.equal(decisions,1);f.events.get("blur")();button(f.render(),"刷新队列与决定").props.onClick();await settle();tree=f.render();assert.match(text(tree),/已只读核实网站的原审核决定/);assert.doesNotMatch(text(tree),/private evidence/);assert.equal(decisions,1)}finally{f.close()}});
