const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const Module = require("node:module");
const path = require("node:path");
const test = require("node:test");
const ts = require("typescript");

function loadTypeScript(relativePath, dependencies = {}) {
  const filename = path.resolve(__dirname, relativePath);
  const compiled = ts.transpileModule(fs.readFileSync(filename, "utf8"), {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true },
    fileName: filename,
  });
  const loaded = new Module(filename, module);
  loaded.filename = filename;
  loaded.paths = Module._nodeModulePaths(path.dirname(filename));
  loaded.require = (name) => Object.hasOwn(dependencies, name)
    ? dependencies[name] : Module.prototype.require.call(loaded, name);
  loaded._compile(compiled.outputText, filename);
  return loaded.exports;
}

const proto = loadTypeScript("../../src/lib/protocol/proto.ts");
const auth = loadTypeScript("../../src/lib/protocol/protocol-auth.ts", { "@/lib/protocol/proto": proto });
// Regenerated by fixtures/protocol-fixture.go using the actual Go SDK signer.
const fixture = JSON.parse(fs.readFileSync(path.resolve(__dirname, "../fixtures/protocol-go.json"), "utf8"));
const bytes = (field) => Buffer.from(fixture[field], "base64");
const privateKey = crypto.createPrivateKey({
  key: Buffer.concat([Buffer.from("302e020100300506032b657004220420", "hex"), bytes("seed")]),
  type: "pkcs8", format: "der",
});
const envelope = () => proto.decodeEncryptedEnvelope(bytes("envelope"));
const registry = () => ({
  urn: fixture.senderUrn, peerId: fixture.peerId,
  x25519Pubkey: Buffer.alloc(32, 0x11), ed25519Pubkey: bytes("publicKey"),
  signature: bytes("registrationSignature"), storesUserData: true,
  timestamp: fixture.registrationTimestamp,
});

test("Go signed protobuf and Node signatures match byte for byte in both directions", () => {
  const env = envelope();
  auth.verifyEnvelope(env, fixture.recipientUrn);
  assert.deepEqual(proto.encodeEncryptedEnvelope(env), bytes("envelope"));
  assert.deepEqual(auth.envelopeSigningBytes(env), bytes("signingBytes"));
  const { signature, senderEd25519Pubkey, ...unsigned } = env;
  const signed = auth.signEnvelope(unsigned, privateKey);
  assert.deepEqual(proto.encodeEncryptedEnvelope(signed), bytes("envelope"));
  assert.equal(unsigned.signature, undefined, "signing must not mutate the caller");
  assert.equal(unsigned.senderEd25519Pubkey, undefined);
  assert.equal(signed.signature.length, 64);
});

test("Go unknown fields and proto3 omitted ciphertext survive signing", () => {
  const encoded = bytes("extendedEnvelope");
  const env = proto.decodeEncryptedEnvelope(encoded);
  assert.equal(env.ciphertext.length, 0);
  assert.equal(env.unknownFields.toString("hex"), "980601a50601020304");
  auth.verifyEnvelope(env, fixture.recipientUrn);
  assert.deepEqual(proto.encodeEncryptedEnvelope(env), encoded);
  assert.deepEqual(proto.encodeEncryptedEnvelope(auth.signEnvelope(env, privateKey)), encoded);
  env.unknownFields[2] ^= 1;
  assert.throws(() => auth.verifyEnvelope(env, fixture.recipientUrn), /signature/);
});

test("every authenticated envelope field rejects tampering", async (t) => {
  for (const field of ["senderUrn", "senderStaticPubkey", "ephemeralPubkey", "nonce", "ciphertext", "tag", "messageId", "recipientUrn", "senderEd25519Pubkey", "signature"]) {
    await t.test(field, () => {
      const env = envelope();
      if (typeof env[field] === "string") env[field] += "x";
      else env[field][0] ^= 1;
      assert.throws(() => auth.verifyEnvelope(env, fixture.recipientUrn));
    });
  }
});

test("self-certifying identity prevents attacker-signed labels and wrong destinations", () => {
  const env = envelope();
  const attacker = crypto.generateKeyPairSync("ed25519");
  assert.throws(() => auth.signEnvelope(env, attacker.privateKey), /sender URN/);
  assert.throws(() => auth.verifyEnvelope(env, "urn:other:destination"), /recipient/);
  assert.throws(() => auth.verifyEnvelope(env, ""), /recipient/);
  assert.throws(() => auth.signEnvelope(env, crypto.generateKeyPairSync("x25519").privateKey), /Ed25519/);
  assert.equal(auth.urnMatchesPublicKey(fixture.senderUrn, bytes("publicKey")), true);
  assert.equal(auth.urnMatchesPublicKey(fixture.senderUrn.replace("urn:hermes:agent:", "urn:custom:namespace:"), bytes("publicKey")), true);
  for (const urn of [fixture.senderUrn + " ", fixture.senderUrn + "\n", fixture.senderUrn + "|", fixture.senderUrn + "\0", "urn:" + fixture.senderUrn.split(":").at(-1)]) {
    assert.equal(auth.urnMatchesPublicKey(urn, bytes("publicKey")), false);
  }
});

test("protobuf retains a UTF-8 BOM inside signed IDs and chat text", () => {
  const env = auth.signEnvelope({ ...envelope(), messageId: "\ufeffmessage-id" }, privateKey);
  const decoded = proto.decodeEncryptedEnvelope(proto.encodeEncryptedEnvelope(env));
  assert.equal(decoded.messageId, "\ufeffmessage-id");
  auth.verifyEnvelope(decoded, fixture.recipientUrn);
  assert.equal(proto.decodeChatMessage(proto.encodeChatMessage("\ufeffhello", 1)).text, "\ufeffhello");
});

test("legacy, invalid lengths, unsafe IDs and oversize envelopes are rejected", () => {
  const valid = envelope();
  assert.throws(() => auth.verifyEnvelope({ ...valid, signature: Buffer.alloc(0) }, fixture.recipientUrn), /signature/);
  for (const field of ["senderStaticPubkey", "ephemeralPubkey", "nonce", "tag"]) {
    assert.throws(() => auth.signEnvelope({ ...valid, [field]: Buffer.alloc(1) }, privateKey), /length/);
  }
  for (const messageId of ["", "x".repeat(257), "中".repeat(86), "line\nbreak", "null\0byte", "carriage\rreturn"]) {
    assert.throws(() => auth.signEnvelope({ ...valid, messageId }, privateKey), /message ID/);
  }
  assert.throws(() => auth.signEnvelope({ ...valid, ciphertext: Buffer.alloc(proto.MAX_ENVELOPE_SIZE) }, privateKey), /size limit/);
  assert.throws(() => proto.decodeEncryptedEnvelope(Buffer.alloc(proto.MAX_ENVELOPE_SIZE + 1)), /size limit/);
  assert.throws(() => proto.encodeEncryptedEnvelope({ ...valid, unknownFields: Buffer.from([0x0a, 0]) }), /Known envelope field/);
});

test("registration matches Go preimage, canonical PeerID and persisted-record verification", () => {
  const record = registry();
  assert.equal(auth.peerIdFromEd25519PublicKey(bytes("publicKey")), fixture.peerId);
  assert.deepEqual(auth.buildRegistrationSigningBytes(record), bytes("registrationSigningBytes"));
  auth.verifyRegistration(record, fixture.senderUrn);
  assert.deepEqual(crypto.sign(null, auth.buildRegistrationSigningBytes(record), privateKey), record.signature);
  assert.throws(() => auth.verifyRegistration(record, "urn:other:agent"), /destination/);
  // A signed persisted record remains valid after the admission time window.
  assert.ok(record.timestamp < Math.floor(Date.now() / 1000) - 300);
});

test("registration rejects all signed field substitutions and forged peer identities", async (t) => {
  const changes = {
    urn: fixture.senderUrn + "x", peerId: fixture.peerId + "x", x25519Pubkey: Buffer.alloc(32, 9),
    ed25519Pubkey: Buffer.alloc(32, 9), signature: Buffer.alloc(64), storesUserData: false,
    timestamp: fixture.registrationTimestamp + 1,
  };
  for (const [field, value] of Object.entries(changes)) {
    await t.test(field, () => assert.throws(() => auth.verifyRegistration({ ...registry(), [field]: value })));
  }
  for (const timestamp of [0, -1, Number.MAX_SAFE_INTEGER + 1, 1.5, NaN, Infinity, "1700000123", 2n ** 63n]) {
    assert.throws(() => auth.verifyRegistration({ ...registry(), timestamp }), /timestamp/);
  }
  for (const field of ["x25519Pubkey", "ed25519Pubkey", "signature"]) {
    assert.throws(() => auth.verifyRegistration({ ...registry(), [field]: Buffer.alloc(1) }));
  }
  assert.throws(() => auth.verifyRegistration({ ...registry(), storesUserData: "true" }), /storage policy/);
});

test("Go ChatMessage metadata and negative int64 timestamps interoperate", () => {
  const expected = {
    text: "你好 Hermes", timestamp: BigInt(fixture.registrationTimestamp),
    conversationId: "conversation-fixture", inReplyTo: "previous-message", taskId: "task-fixture",
    kind: "result", deadline: "2030-01-02T03:04:05Z", hopLimit: 3,
  };
  assert.deepEqual(proto.decodeChatMessage(bytes("chat")), expected);
  const { text, timestamp, ...metadata } = expected;
  assert.deepEqual(proto.encodeChatMessage(text, timestamp, metadata), bytes("chat"));
  assert.deepEqual(proto.decodeChatMessage(bytes("negativeTimestampChat")), { text: "", timestamp: -1n });
  assert.deepEqual(proto.encodeChatMessage("", -1), bytes("negativeTimestampChat"));
  assert.deepEqual(proto.encodeChatMessage("", 0), bytes("emptyChat"));
  assert.deepEqual(proto.decodeChatMessage(proto.encodeChatMessage("Plain message", 12)), { text: "Plain message", timestamp: 12n });
  assert.deepEqual(proto.decodeChatMessage(proto.encodeChatMessage("{ordinary JSON}", 0)), { text: "{ordinary JSON}", timestamp: 0n });
  assert.deepEqual(proto.decodeChatMessage(proto.encodeChatMessage("terminal", 0, { hopLimit: 0 })), { text: "terminal", timestamp: 0n, hopLimit: 0 });
});

test("chat validates complete protobuf buffers, oneof bodies and authenticated metadata", () => {
  const text = proto.encodeChatMessage("hello", 1);
  assert.throws(() => proto.decodeChatMessage(Buffer.concat([text, Buffer.from([0x12, 0x7f])])), /Truncated/);
  const raw = Buffer.from([0x9a, 0x06, 0x03, 1, 2, 3]);
  assert.deepEqual(proto.decodeChatMessage(Buffer.concat([text, raw])), { raw: Buffer.from([1, 2, 3]) });
  assert.deepEqual(proto.decodeChatMessage(Buffer.concat([raw, text])), { text: "hello", timestamp: 1n });
  for (const metadata of [{ hopLimit: -1 }, { hopLimit: 65 }, { hopLimit: 1.5 }, { taskId: "中".repeat(86) }, { conversationId: null }, { deadline: "tomorrow" }, { deadline: "2030-02-30T00:00:00Z" }, { deadline: "2030-01-01T24:00:00Z" }]) {
    assert.throws(() => proto.encodeChatMessage("hello", 0, metadata));
  }
  for (const document of [{ agent_comm: 1 }, { agent_comm: 1, text: 42 }, { agent_comm: 1, text: "hello", hop_limit: -1 }, { agent_comm: 1, text: "hello", task_id: {} }]) {
    assert.throws(() => proto.decodeChatMessage(proto.encodeChatMessage(JSON.stringify(document), 0)));
  }
  assert.throws(() => proto.encodeChatMessage("x".repeat(262145), 0), /size limit/);
  assert.throws(() => proto.encodeTextMessage("hello", 2n ** 63n), /int64/);
  assert.throws(() => proto.encodeTextMessage("hello", Number.MAX_SAFE_INTEGER + 1), /safe integer/);
});

test("protobuf rejects truncation, oversized varints, bad tags, wrong wire types, duplicates and invalid UTF-8", () => {
  for (const malformed of [
    [0x0a, 0x05, 0x41], // Declared bytes run off the buffer.
    [0x0a, 0xff, 0xff, 0xff, 0xff, 0x7f], // Oversized length.
    [0x80], // Truncated tag.
    [0x0a, ...Array(10).fill(0x80)], // Unbounded varint attack.
    [...Array(9).fill(0x80), 0x02], // Overflow in byte ten.
    [0x00], // Forbidden field number zero.
    [0x08, 0x01], // Wrong wire type on known sender field.
    [0x0a, 0x00, 0x0a, 0x00], // Duplicate sender identity.
    [0x0a, 0x02, 0xc0, 0xaf], // Invalid UTF-8.
    [0x58, 0x80], // Truncated unknown varint field.
    [0x59, 0x01], // Truncated unknown fixed64 field.
    [0x5d, 0x01], // Truncated unknown fixed32 field.
    [0x5b], // Unsupported group wire format.
  ]) assert.throws(() => proto.decodeEncryptedEnvelope(Buffer.from(malformed)));
});
